homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude
  longitude: !secret longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: !secret elevation
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Berlin
  customize: !include customize.yaml



#  ██████╗ ██████╗  ██████╗ ██╗   ██╗██████╗ ███████╗
# ██╔════╝ ██╔══██╗██╔═══██╗██║   ██║██╔══██╗██╔════╝
# ██║  ███╗██████╔╝██║   ██║██║   ██║██████╔╝███████╗
# ██║   ██║██╔══██╗██║   ██║██║   ██║██╔═══╝ ╚════██║
# ╚██████╔╝██║  ██║╚██████╔╝╚██████╔╝██║     ███████║
#  ╚═════╝ ╚═╝  ╚═╝ ╚═════╝  ╚═════╝ ╚═╝     ╚══════╝
                                                   
group:
  travel:
    name: Commute
    entities:
      - sensor.ost_to_pots_next

  living_room:
    name: Living Room
    entities:
      - light.safari
      - light.tall_top
      - light.tall_bottom

  kitchen:
    name: Kitchen
    entities:
      - light.kitchen

  work_room:
    name: Work Room
    entities:
      - light.work_room
      - light.edgy
      - light.hexacompy_case
      - switch.hexacompy_monitors
      
  bedroom:
    name: Bedroom
    entities:
      - light.death_star
      - light.infinity

  bathroom:
    name: Bathroom
    entities:
      - switch.radiator

  weather:
    name: Weather
    entities:
      - sensor.pws_weather
      - sensor.pws_temp_c
      - sensor.pws_feelslike_c
      - sensor.pws_relative_humidity
      - sensor.pws_wind_kph
      - sensor.pws_visibility_km
      - sensor.pws_pressure_mb

  rpi2:
    name: Raspberry Pi 2
    entities:
      - sensor.cpu_use
      - sensor.disk_free_
      - sensor.ram_free
      - sensor.received_eth0
      - sensor.sent_eth0

  limitless:
    name: LimitlessLED Lights
    control: hidden
    entities:
      # - light.safari
      # - light.tall_top
      # - light.tall_bottom
      # - light.death_star
      - light.infinity
      - light.bed_strip
      - light.kitchen
      # - light.work_room

  lights_off_startup:
    name: Lights that are off on startup
    control: hidden
    entities:
      - group.kitchen
      # - group.work_room
      - group.bedroom



# Show links to resources in log and frontend
#introduction:

# Enables the frontend
frontend:

http:
  # Uncomment this to add a password (recommended!)
  api_password: !secret api_password
  # Uncomment this if you are using SSL or running in Docker etc
  # base_url: example.duckdns.org:8123

# Checks for available updates
updater:

# Discover some devices automatically
# discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# recorder:
#   db_url: !secret db_url

influxdb:
  host: !secret influx_host
  # username: !secret influx_username
  # password: !secret influx_password

# Enables support for tracking state changes over time.
# history:

config:

# View all events in a logbook
# logbook:

# Track the sun
sun:

# Google Home
# emulated_hue:

# apiai:
#   intents:
#     smarthome.lights.switch.on:
#       speech: Turned on {{ room }} lights
#       async_action: True
#       action:
#         service: light.turn_on
#         data_template:
#           entity_id: "group.{{ room | replace(' ', '_') }}"        
#     smarthome.lights.switch.off:
#       speech: Turned off {{ room }} lights
#       async_action: True
#       action:
#         service: light.turn_off
#         data_template:
#           entity_id: "group.{{ room | replace(' ', '_') }}"



# ███████╗███████╗███╗   ██╗███████╗ ██████╗ ██████╗ ███████╗
# ██╔════╝██╔════╝████╗  ██║██╔════╝██╔═══██╗██╔══██╗██╔════╝
# ███████╗█████╗  ██╔██╗ ██║███████╗██║   ██║██████╔╝███████╗
# ╚════██║██╔══╝  ██║╚██╗██║╚════██║██║   ██║██╔══██╗╚════██║
# ███████║███████╗██║ ╚████║███████║╚██████╔╝██║  ██║███████║
# ╚══════╝╚══════╝╚═╝  ╚═══╝╚══════╝ ╚═════╝ ╚═╝  ╚═╝╚══════╝

binary_sensor:

  - platform: mqtt
    name: "Top Right"
    state_topic: "switch/topRight"

  - platform: mqtt
    name: "Bottom Right"
    state_topic: "switch/bottomRight"

  - platform: mqtt
    name: "Top Left"
    state_topic: "switch/topLeft"

  - platform: mqtt
    name: "Bottom Left"
    state_topic: "switch/bottomLeft"

  - platform: mqtt
    name: "InfoMatrix Online"
    state_topic: "devices/infomatrix/$online"
    payload_on: 'true'
    payload_off: 'false'

sensor:

  - platform: mqtt
    state_topic: "devices/envsense/temperature/value"
    name: "Temp"
    unit_of_measurement: "°C"

  - platform: mqtt
    state_topic: "devices/envsense/temperature/valueRaw"
    name: "Temp (Raw)"
    unit_of_measurement: "°C"
    # expire_after: 300

  - platform: mqtt
    state_topic: "devices/envsense/humidity/value"
    name: "Humidity"
    unit_of_measurement: "%"
    # expire_after: 300

  - platform: mqtt
    state_topic: "devices/envsense/pressure/value"
    name: "Pressure"
    unit_of_measurement: "hPa"
    # expire_after: 300

  - platform: mqtt
    state_topic: "devices/envsense/light/value"
    name: "Light"
    unit_of_measurement: "%"
    # expire_after: 300

  - platform: mqtt
    state_topic: "devices/plantsense/moisture/value"
    name: "Plant Moisture"
    unit_of_measurement: "%"

  - platform: wunderground
    api_key: !secret wunderground_key
    monitored_conditions:
      - alerts
      - dewpoint_c
      - feelslike_c
      - heat_index_c
      - precip_1hr_metric
      - precip_today_metric
      - pressure_mb
      - pressure_trend
      - relative_humidity
      - solarradiation
      - temp_c
      - UV
      - visibility_km
      - weather
      - wind_degrees
      - wind_dir
      - wind_gust_kph
      - wind_kph

  - platform: darksky
    api_key: !secret darksky_key
    latitude: !secret latitude
    longitude: !secret longitude
    update_interval:
      minutes: 10
    monitored_conditions:
      - summary
      - icon
      - nearest_storm_distance
      - precip_type
      - precip_intensity
      - precip_probability
      - temperature
      - apparent_temperature
      - dew_point
      - wind_speed
      - wind_bearing
      - pressure
      - visibility
      - humidity
      - cloud_cover
      - minutely_summary
      - hourly_summary
      - daily_summary
      - temperature_min
      - temperature_max
      - apparent_temperature_min
      - apparent_temperature_max
      - precip_intensity_max

  - platform: systemmonitor
    resources:
      - type: disk_free
        arg: /
      - type: memory_free
      - type: processor_use
      - type: network_in
        arg: eth0
      - type: network_out
        arg: eth0



# Text to speech
tts:
  platform: google




snips:

intent_script:
  ActivateLightColor:
    action:
      - service: light.turn_on
        data_template:
          entity_id: light.{{ objectLocation | replace(" ","_") }}
          # color_name: {{ objectColor }}

  ActivateObject:
    action:
      - service: light.turn_on
        data_template:
          entity_id: light.{{ objectType | replace(" ","_") }}
      - service: switch.turn_on
        data_template:
          entity_id: switch.{{ objectType | replace(" ","_") }}
      - service: light.turn_on
        data_template:
          entity_id: group.{{ objectLocation | replace(" ","_") }}

  DeactivateObject:
    action:
      - service: light.turn_off
        data_template:
          entity_id: light.{{ objectType | replace(" ","_") }}
      - service: switch.turn_off
        data_template:
          entity_id: switch.{{ objectType | replace(" ","_") }}
      - service: light.turn_off
        data_template:
          entity_id: group.{{ objectLocation | replace(" ","_") }}

  # DeactivateObject:
  #   action:
  #     - condition: template
  #       value_template: '{{ objectType == "light" }}'
  #     - service: light.turn_off
  #       data_template:
  #         entity_id: light.{{ objectLocation | replace(" ","_") }}




automation: !include automations.yaml

  
switch:
  - platform: mqtt
    name: "Hexacompy Monitors"
    command_topic: "hexacompy/monitor/all/power/command"
    state_topic: "hexacompy/monitor/all/power/state"

  - platform: tplink
    name: "Radiator"
    host: 192.168.1.157

light:

  - platform: mqtt
    name: "Dell U2515H"
    command_topic: "hexacompy/monitor/U2515H/power/command"
    state_topic: "hexacompy/monitor/U2515H/power/state"
    brightness_command_topic: "hexacompy/monitor/U2515H/brightness/command"
    brightness_state_topic: "hexacompy/monitor/U2515H/brightness/state"

  # - platform: mqtt
  #   name: "Samsung 226BW"
  #   command_topic: "hexacompy/monitor/MEDEL/power/command"
  #   state_topic: "hexacompy/monitor/MEDEL/power/state"
  #   brightness_command_topic: "hexacompy/monitor/MEDEL/brightness/command"
  #   brightness_state_topic: "hexacompy/monitor/MEDEL/brightness/state"

  - platform: mqtt_json
    name: Work Room
    command_topic: "devices/limitless/0x3801/rgb_cct/1/command"
    state_topic: "devices/limitless/0x3801/rgb_cct/1/state"
    brightness: true
    color_temp: true
    rgb: true

  - platform: mqtt_json
    name: Edgy
    command_topic: "devices/limitless/0x3801/rgbw/3/command"
    state_topic: "devices/limitless/0x3801/rgbw/3/state"
    brightness: true
    rgb: true

  - platform: mqtt_json
    name: Hexacompy Case
    command_topic: "devices/limitless/0x3801/rgb_cct/2/command"
    state_topic: "devices/limitless/0x3801/rgb_cct/2/state"
    brightness: true
    rgb: true

  - platform: mqtt_json
    name: Safari
    command_topic: "devices/limitless/0x3802/rgb_cct/1/command"
    state_topic: "devices/limitless/0x3802/rgb_cct/1/state"
    brightness: true
    color_temp: true
    rgb: true

  - platform: mqtt_json
    name: Tall Top
    command_topic: "devices/limitless/0x3803/rgbw/2/command"
    state_topic: "devices/limitless/0x3803/rgbw/2/state"
    brightness: true
    rgb: true

  - platform: mqtt_json
    name: Tall Bottom
    command_topic: "devices/limitless/0x3803/rgbw/1/command"
    state_topic: "devices/limitless/0x3803/rgbw/1/state"
    brightness: true
    rgb: true

  - platform: mqtt_json
    name: Death Star
    command_topic: "devices/limitless/0x3804/rgb_cct/1/command"
    state_topic: "devices/limitless/0x3804/rgb_cct/1/state"
    brightness: true
    color_temp: true
    rgb: true

  - platform: limitlessled
    bridges:

      - host: !secret limitless_v6_ip
        port: 5987
        version: 6
        groups:
        - number: 1
          type: bridge-led
          name: Bridge Light
        # - number: 1
        #   type: rgbww
        #   name: Safari
        - number: 2
          type: rgbww
          name: Kitchen
        # - number: 3
        #   type: rgbww
        #   name: Work Room
        - number: 4
          type: rgbww
          name: Bed Strip
          fade: on

      - host: !secret limitless_v5_ip
        port: 8899
        version: 5
        groups:
        # - number: 1
        #   type: rgbw
        #   name: Death Star
        # - number: 2
        #   type: rgbw
        #   name: Tall Top
        # - number: 3
        #   type: rgbw
        #   name: Tall Bottom
        - number: 4
          type: rgbw
          name: Infinity
          fade: on


mqtt:
  broker: !secret mqtt_broker
  port: 1883
  client_id: home-assistant
  keepalive: 60
  username: !secret mqtt_user
  password: !secret mqtt_pass
  protocol: 3.1
  birth_message:
    topic: 'ha/status'
    payload: 'online'
    qos: 1
    retain: true
  will_message:
    topic: 'ha/status'
    payload: 'offline'
    qos: 1
    retain: true



# ███████╗ ██████╗███████╗███╗   ██╗███████╗███████╗
# ██╔════╝██╔════╝██╔════╝████╗  ██║██╔════╝██╔════╝
# ███████╗██║     █████╗  ██╔██╗ ██║█████╗  ███████╗
# ╚════██║██║     ██╔══╝  ██║╚██╗██║██╔══╝  ╚════██║
# ███████║╚██████╗███████╗██║ ╚████║███████╗███████║
# ╚══════╝ ╚═════╝╚══════╝╚═╝  ╚═══╝╚══════╝╚══════╝
                                                  
scene:
  - name: Movie Time Start
    entities:
      light.safari: off
      light.tall_top: off
      light.tall_bottom: on
  - name: Movie Time End
    entities:
      light.safari: on
      light.tall_top: off
      light.tall_bottom: off
  - name: Bed Time
    entities:
      group.living_room: off
      group.kitchen: off
      group.work_room: off
      light.infinity: on
  - name: Sleep
    entities:
      group.all_lights: off
      group.all_switches: off
  - name: Morning
    entities:
      light.infinity:
        state: on
        transition: 300

