homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude
  longitude: !secret longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: !secret elevation
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Berlin

  customize:

  # Groups
    group.lights_off_startup:
      hidden: true

    group.limitless:
      hidden: true

    binary_sensor.bottom_left:
      hidden: true

    binary_sensor.bottom_right:
      hidden: true

    binary_sensor.top_left:
      hidden: true

    binary_sensor.top_right:
      hidden: true

  # Weather

    sensor.pws_alerts:
      friendly_name: Alerts

    sensor.pws_dewpoint_c:
      friendly_name: Dewpoint
      icon: mdi:water

    sensor.pws_feelslike_c:
      friendly_name: Feels

    sensor.pws_heat_index_c:
      friendly_name: Heat Index

    sensor.pws_precip_1hr_metric:
      friendly_name: Rain 1h
      icon: mdi:weather-rainy

    sensor.pws_precip_today_metric:
      friendly_name: Rain Today
      icon: mdi:weather-rainy

    sensor.pws_pressure_mb:
      friendly_name: Pressure
      icon: mdi:gauge

    sensor.pws_pressure_trend:
      friendly_name: Pressure Trend
      icon: mdi:gauge

    sensor.pws_relative_humidity:
      friendly_name: Humidity
      icon: mdi:water-percent

    sensor.pws_solarradiation:
      friendly_name: Radiation
      icon: mdi:white-balance-sunny

    sensor.pws_UV:
      friendly_name: UV
      icon: mdi:white-balance-sunny

    sensor.pws_visibility_km:
      friendly_name: Visibility
      icon: mdi:eye

    sensor.pws_weather:
      friendly_name: Weather

    sensor.pws_wind_degrees:
      friendly_name: Wind Angle
      icon: mdi:weather-windy

    sensor.pws_wind_dir:
      friendly_name: Wind Direction
      icon: mdi:weather-windy

    sensor.pws_wind_gust_kph:
      friendly_name: Wind Gust
      icon: mdi:weather-windy

    sensor.pws_wind_kph:
      friendly_name: Wind
      icon: mdi:weather-windy

    sensor.pws_temp_c:
      friendly_name: Temp
      icon: mdi:temperature-celsius


    # Rpi2
    
    sensor.received_eth0:
      friendly_name: Net In

    sensor.sent_eth0:
      friendly_name: Net Out

    sensor.disk_free_:
      friendly_name: Disk Free



#  ██████╗ ██████╗  ██████╗ ██╗   ██╗██████╗ ███████╗
# ██╔════╝ ██╔══██╗██╔═══██╗██║   ██║██╔══██╗██╔════╝
# ██║  ███╗██████╔╝██║   ██║██║   ██║██████╔╝███████╗
# ██║   ██║██╔══██╗██║   ██║██║   ██║██╔═══╝ ╚════██║
# ╚██████╔╝██║  ██║╚██████╔╝╚██████╔╝██║     ███████║
#  ╚═════╝ ╚═╝  ╚═╝ ╚═════╝  ╚═════╝ ╚═╝     ╚══════╝
                                                   
group:
  travel:
    name: Commute
    entities:
      - sensor.ost_to_pots_next

  living_room:
    name: Living Room
    entities:
      - light.safari
      - switch.hexacompy_monitors
      - light.tall_top
      - light.tall_bottom

  kitchen:
    name: Kitchen
    entities:
      - light.kitchen

  other_room:
    name: Other Room ™
    entities:
      - light.other_room
      
  bedroom:
    name: Bedroom
    entities:
      - light.death_star
      - light.infinity
      - light.bed_strip

  weather:
    name: Weather
    entities:
      - sensor.pws_weather
      - sensor.pws_temp_c
      - sensor.pws_feelslike_c
      - sensor.pws_relative_humidity
      - sensor.pws_wind_kph
      - sensor.pws_visibility_km
      - sensor.pws_pressure_mb

  rpi2:
    name: Raspberry Pi 2
    entities:
      - sensor.cpu_use
      - sensor.disk_free_
      - sensor.ram_free
      - sensor.received_eth0
      - sensor.sent_eth0

  limitless:
    name: LimitlessLED Lights
    control: hidden
    entities:
      - light.safari
      - light.tall_top
      - light.tall_bottom
      - light.death_star
      - light.infinity
      - light.bed_strip
      - light.kitchen
      - light.other_room

  lights_off_startup:
    name: Lights that are off on startup
    control: hidden
    entities:
      - group.kitchen
      - group.other_room
      - group.bedroom



# Show links to resources in log and frontend
#introduction:

# Enables the frontend
frontend:

http:
  # Uncomment this to add a password (recommended!)
  api_password: !secret api_password
  # Uncomment this if you are using SSL or running in Docker etc
  # base_url: example.duckdns.org:8123

# Checks for available updates
updater:

# Discover some devices automatically
# discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

recorder:
  db_url: !secret db_url

influxdb:
  host: !secret influx_host
  username: !secret influx_username
  password: !secret influx_password

# Enables support for tracking state changes over time.
history:

config:

# View all events in a logbook
logbook:

# Track the sun
sun:

# Google Home
# emulated_hue:

# apiai:
#   intents:
#     smarthome.lights.switch.on:
#       speech: Turned on {{ room }} lights
#       async_action: True
#       action:
#         service: light.turn_on
#         data_template:
#           entity_id: "group.{{ room | replace(' ', '_') }}"        
#     smarthome.lights.switch.off:
#       speech: Turned off {{ room }} lights
#       async_action: True
#       action:
#         service: light.turn_off
#         data_template:
#           entity_id: "group.{{ room | replace(' ', '_') }}"



# ███████╗███████╗███╗   ██╗███████╗ ██████╗ ██████╗ ███████╗
# ██╔════╝██╔════╝████╗  ██║██╔════╝██╔═══██╗██╔══██╗██╔════╝
# ███████╗█████╗  ██╔██╗ ██║███████╗██║   ██║██████╔╝███████╗
# ╚════██║██╔══╝  ██║╚██╗██║╚════██║██║   ██║██╔══██╗╚════██║
# ███████║███████╗██║ ╚████║███████║╚██████╔╝██║  ██║███████║
# ╚══════╝╚══════╝╚═╝  ╚═══╝╚══════╝ ╚═════╝ ╚═╝  ╚═╝╚══════╝

binary_sensor:

  - platform: mqtt
    name: "Top Right"
    state_topic: "switch/topRight"

  - platform: mqtt
    name: "Bottom Right"
    state_topic: "switch/bottomRight"

  - platform: mqtt
    name: "Top Left"
    state_topic: "switch/topLeft"

  - platform: mqtt
    name: "Bottom Left"
    state_topic: "switch/bottomLeft"

sensor:

  - platform: mqtt
    state_topic: "devices/envsense/temperature/value"
    name: "Temp"
    unit_of_measurement: "°C"
    # expire_after: 300

  - platform: mqtt
    state_topic: "devices/envsense/humidity/value"
    name: "Humidity"
    unit_of_measurement: "%"
    # expire_after: 300

  - platform: mqtt
    state_topic: "devices/envsense/pressure/value"
    name: "Pressure"
    unit_of_measurement: "hPa"
    # expire_after: 300

  - platform: mqtt
    state_topic: "devices/envsense/light/value"
    name: "Light"
    unit_of_measurement: "%"
    # expire_after: 300


  - platform: wunderground
    api_key: !secret wunderground_key
    monitored_conditions:
      - alerts
      - dewpoint_c
      - feelslike_c
      - heat_index_c
      - precip_1hr_metric
      - precip_today_metric
      - pressure_mb
      - pressure_trend
      - relative_humidity
      - solarradiation
      - temp_c
      - UV
      - visibility_km
      - weather
      - wind_degrees
      - wind_dir
      - wind_gust_kph
      - wind_kph

  - platform: systemmonitor
    resources:
      - type: disk_free
        arg: /
      - type: memory_free
      - type: processor_use
      - type: network_in
        arg: eth0
      - type: network_out
        arg: eth0



# Text to speech
tts:
  platform: google

automation:
  - alias: "Lights on start"
    trigger:
      platform: homeassistant
      event: start
    action:
      - service: homeassistant.turn_on
        entity_id: group.limitless
        data:
          color_temp: 254
      - service: homeassistant.turn_on
        entity_id: light.bed_strip
        data:
          color_name: orange
      - service: homeassistant.turn_off
        entity_id: group.lights_off_startup
  
  - alias: "Bedroom lights on"
    trigger:
      - platform: state
        entity_id: binary_sensor.top_left
        from: "off"
        to: "on"
    action:
      service: light.turn_on
      entity_id: group.bedroom

  - alias: "Bedroom lights off"
    trigger:
      - platform: state
        entity_id: binary_sensor.bottom_left
        from: "off"
        to: "on"
    action:
      service: light.turn_off
      entity_id: group.bedroom

  - alias: "Bedroom infinity light toggle"
    trigger:
      - platform: state
        entity_id: binary_sensor.top_right
        from: "off"
        to: "on"
    action:
      service: light.toggle
      entity_id: light.infinity

  - alias: "Bedroom bed strip toggle"
    trigger:
      - platform: state
        entity_id: binary_sensor.bottom_right
        from: "off"
        to: "on"
    action:
      service: light.toggle
      entity_id: light.bed_strip

  - alias: "Long bottom press sleep time"
    trigger:
      - platform: state
        entity_id: binary_sensor.bottom_left, binary_sensor.bottom_right
        from: "off"
        to: "on"
        for:
          seconds: 2
    action:
      service: scene.turn_on
      entity_id: scene.sleep

  # - alias: "Turn on lights on Hexacompy wakeup"
  #   trigger:
  #     - platform: state
  #       entity_id: switch.hexacompy_monitors
  #       state: "on"
  #   action:
  #     service: light.turn_on
  #     entity_id: light.safari

switch:
  - platform: mqtt
    name: "Hexacompy Monitors"
    command_topic: "hexacompy/monitor/all/power/command"
    state_topic: "hexacompy/monitor/all/power/state"

light:

  # - platform: mqtt
  #   name: "Dell U2515H"
  #   command_topic: "hexacompy/monitor/U2515H/power/command"
  #   state_topic: "hexacompy/monitor/U2515H/power/state"
  #   brightness_command_topic: "hexacompy/monitor/U2515H/brightness/command"
  #   brightness_state_topic: "hexacompy/monitor/U2515H/brightness/state"

  # - platform: mqtt
  #   name: "Samsung 226BW"
  #   command_topic: "hexacompy/monitor/MEDEL/power/command"
  #   state_topic: "hexacompy/monitor/MEDEL/power/state"
  #   brightness_command_topic: "hexacompy/monitor/MEDEL/brightness/command"
  #   brightness_state_topic: "hexacompy/monitor/MEDEL/brightness/state"

  - platform: limitlessled
    bridges:

      - host: !secret limitless_v6_ip
        port: 5987
        version: 6
        groups:
        - number: 1
          type: rgbww
          name: Safari
        - number: 2
          type: rgbww
          name: Kitchen
        - number: 3
          type: rgbww
          name: Other Room
        - number: 4
          type: rgbww
          name: Bed Strip
          fade: on

      - host: !secret limitless_v5_ip
        port: 8899
        version: 5
        groups:
        - number: 1
          type: rgbw
          name: Tall Top
        - number: 2
          type: rgbw
          name: Tall Bottom
        - number: 3
          type: rgbw
          name: Death Star
        - number: 4
          type: rgbw
          name: Infinity
          fade: on


mqtt:
  broker: !secret mqtt_broker
  port: 1883
  client_id: home-assistant
  keepalive: 60
  username: !secret mqtt_user
  password: !secret mqtt_pass
  protocol: 3.1
  birth_message:
    topic: 'ha/status'
    payload: 'online'
    qos: 1
    retain: true
  will_message:
    topic: 'ha/status'
    payload: 'offline'
    qos: 1
    retain: true



# ███████╗ ██████╗███████╗███╗   ██╗███████╗███████╗
# ██╔════╝██╔════╝██╔════╝████╗  ██║██╔════╝██╔════╝
# ███████╗██║     █████╗  ██╔██╗ ██║█████╗  ███████╗
# ╚════██║██║     ██╔══╝  ██║╚██╗██║██╔══╝  ╚════██║
# ███████║╚██████╗███████╗██║ ╚████║███████╗███████║
# ╚══════╝ ╚═════╝╚══════╝╚═╝  ╚═══╝╚══════╝╚══════╝
                                                  
scene:
  - name: Bed Time
    entities:
      group.all_lights: off
      group.all_switches: off
      group.bedroom: on
  - name: Sleep
    entities:
      group.all_lights: off
      group.all_switches: off
  - name: Morning
    entities:
      group.bedroom: on

